controller_list:
  - name: fake_arm_controller_controller
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
  - name: fake_grippper_controller_controller
    joints:
      - gripper_finger1_joint
initial:  # Define initial robot poses.
  - group: arm_controller
    pose: straightUp
  - group: grippper_controller
    pose: close