# controller_frequency: 4.0
# TrajectoryPlannerROS:
#   max_vel_x: 0.6
#   min_vel_x: 0.0016
#   max_vel_theta: 6.0
#   min_vel_theta: -6.0
#   min_in_place_vel_theta: 4.0
#   acc_lim_x: 4.7
#   acc_lim_y: 0
#   holonomic_robot: false
#   dwa: false
#   escape_vel: -0.15
#   goal_distance_bias: 4.6
#   path_distance_bias: 3.4
#   vtheta_samples: 65
#   vx_samples: 25
#   sim_time: 1.5
#   yaw_goal_tolerance: 0.05
#   xy_goal_tolerance: 0.2
# SHAXPY
controller_frequency: 4.0
TrajectoryPlannerROS:
  max_vel_x: 0.6
  min_vel_x: 0.1
  max_vel_theta: 6.0
  min_vel_theta: -6.0
  min_in_place_vel_theta: 4.0
  acc_lim_x: 4.7
  acc_lim_y: 0
  holonomic_robot: false
  dwa: false
  # goal_distance_bias: 2.3
  # path_distance_bias: 1.57
  goal_distance_bias: 1.57
  path_distance_bias: 2.0
  vtheta_samples: 65
  vx_samples: 25
  sim_time: 1.5
  yaw_goal_tolerance: 0.05
  xy_goal_tolerance: 0.2
