obstacle_range: 3.5
raytrace_range: 4.0
footprint: [[-0.310, -0.26], [-0.310, 0.26], [0.310, 0.26], [0.310, -0.26]]
inflation_radius: 0.25
transform_tolerance: 0.5

observation_sources: scan
scan:
  data_type: LaserScan
  topic: /ebot/laser/scan
  marking: true
  clearing: true

map_type: costmap
