TrajectoryPlannerROS:
  max_vel_x: 0.16
  min_vel_x: 0.02
  max_vel_theta: 3.2
  min_vel_theta: -3.2
  min_in_place_vel_theta: 2.5
  acc_lim_theta: 3.2
  acc_lim_x: 2.5
  acc_lim_y: 0
  holonomic_robot: false
  dwa: false
  goal_distance_bias: 3.8
  path_distance_bias: 3.65
  vtheta_samples: 20
  vx_samples: 20
  yaw_goal_tolerance: 0.3
  xy_goal_tolerance: 0.3
