controller_frequency: 5.0
TrajectoryPlannerROS:
  max_vel_x: 0.3
  min_vel_x: 0.05
  max_vel_theta: 5.0
  min_vel_theta: -5.0
  min_in_place_vel_theta: 3.0
  acc_lim_theta: 4.2
  acc_lim_x: 2.5
  acc_lim_y: 0
  holonomic_robot: false
  dwa: false
  goal_distance_bias: 4.5
  path_distance_bias: 4.5
  vtheta_samples: 40
  vx_samples: 20
  yaw_goal_tolerance: 0.3
  xy_goal_tolerance: 0.3
