local_costmap:
  global_frame: odom
  robot_base_frame: ebot_base
  update_frequency: 3.5 #before 5.0
  publish_frequency: 2.2 #before 2.0
  static_map: false
  rolling_window: true
  width: 3.0
  height: 3.0
  resolution: 0.05 #increase to for higher res 0.025
  transform_tolerance: 0.55
  cost_scaling_factor: 2.85
  inflation_radius: 0.75
#  neutral cost: 66
#  lethal cost: 222

# SHAXPY
# local_costmap:
#   global_frame: odom
#   robot_base_frame: ebot_base
#   update_frequency: 3.5 #before 5.0
#   publish_frequency: 2.0 #before 2.0
#   static_map: false
#   rolling_window: true
#   width: 2.5
#   height: 2.5
#   resolution: 0.05 #increase to for higher res 0.025
#   transform_tolerance: 0.5
#   cost_scaling_factor: 3.65
#   inflation_radius: 0.8
#   neutral cost: 66
#   lethal cost: 253
