
controller_frequency: 4.0
TrajectoryPlannerROS:
  max_vel_x: 0.48
  min_vel_x: 0.002
  max_vel_theta: 6.0
  min_vel_theta: -6.0
  min_in_place_vel_theta: 4.0
  acc_lim_x: 4.7
  acc_lim_y: 0
  holonomic_robot: false
  dwa: false
  goal_distance_bias: 4.6
  path_distance_bias: 3.4
  vtheta_samples: 50
  vx_samples: 25
  sim_time: 1.5
  yaw_goal_tolerance: 0.6
  xy_goal_tolerance: 0.22
