global_costmap:
  global_frame: map
  robot_base_frame: ebot_base
  update_frequency: 3.0 #before: 5.0
  publish_frequency: 0.5 #before 0.5
  static_map: true
  transform_tolerance: 0.5
  cost_scaling_factor: 0.15
  inflation_radius: 0.55
  neutral cost : 30
  lethal cost: 253
