controller_frequency: 4.0
recovery_behaviour_enabled: true
NavfnROS:
    # Specifies whether or not to allow navfn to create plans that traverse unknown space.
  default_tolerance: 0.21 
TrajectoryPlannerROS:
  max_vel_x: 0.4
  min_vel_x: 0.07
  max_vel_theta: 5.0
  min_vel_theta: -5.0
  min_in_place_vel_theta: 5.0
  acc_lim_theta: 3.0
  acc_lim_x: 2.8
  acc_lim_y: 0
  holonomic_robot: false
  dwa: false
  goal_distance_bias: 4.5
  path_distance_bias: 4.5
  vtheta_samples: 50
  vx_samples: 20
  yaw_goal_tolerance: 0.28
  xy_goal_tolerance: 0.28
  sim_time: 1.8
  controller_frequency: 20.0
  meter_scoring: true
  pdist_scale: 0.12
  simple_attractor: false
  publish_cost_grid_pc: true
  oscillation_reset_dist: 0.3
  escape_reset_dist: 0.12
  escape_reset_theta: 0.1
